export const lorem = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet viverra erat, a hendrerit enim. Fusce et iaculis nisi. Suspendisse tristique mauris sit amet urna blandit tristique. Donec urna magna, tempus et odio id, lobortis aliquet ipsum. Nullam vitae aliquam est. Pellentesque venenatis fringilla nibh, nec convallis nunc convallis ut. Ut hendrerit dapibus vestibulum. Quisque ac condimentum quam. Morbi consequat tellus a semper vehicula. Donec ornare molestie aliquam.

    Nullam in risus eget ipsum gravida molestie. Nulla lobortis congue maximus. Aliquam ultricies imperdiet libero nec hendrerit. Donec feugiat egestas interdum. Donec eros eros, volutpat vitae ligula et, placerat lacinia orci. Phasellus at dui leo. Sed maximus, ipsum a hendrerit convallis, sapien velit suscipit arcu, vel ullamcorper erat orci eget lacus.
    
    Suspendisse interdum velit pretium nibh sodales molestie. Donec blandit erat blandit velit vulputate scelerisque. Proin nec luctus quam. Nam ac libero odio. Aliquam eu sodales quam. Duis scelerisque molestie sagittis. Donec porta ex ut sollicitudin mattis. Maecenas finibus molestie nibh eget pellentesque. Cras sagittis gravida enim a vehicula. Sed a maximus nibh. Proin ut dolor elementum, hendrerit lorem a, lobortis urna. Quisque feugiat dui est, et finibus lectus pellentesque vel. Pellentesque et neque tellus. Nam magna eros, facilisis ut sem quis, rutrum vestibulum ante.
    
    Sed at viverra urna. Morbi et quam quis erat condimentum tristique vel vel nibh. In ante magna, ultricies eget imperdiet vitae, consectetur ac augue. Proin ex quam, auctor vel nunc in, molestie rhoncus elit. Vivamus commodo suscipit accumsan. Donec vulputate vitae arcu ut semper. In risus velit, tristique ut massa quis, consequat consequat ipsum. Praesent erat arcu, commodo ut massa luctus, tincidunt pharetra augue. Mauris lacus risus, pharetra eu pharetra sit amet, placerat id mi.
    
    Fusce non ultricies lorem. Nulla eu turpis ut diam sodales interdum vel ut neque. Praesent luctus diam sed sapien dapibus auctor. Praesent at ante eu sapien tincidunt iaculis. Maecenas vitae sapien eget ex interdum lacinia. Quisque et diam et eros luctus blandit. Ut eu justo ultricies, lobortis ex vel, dictum mauris. Sed elit diam, tempus sit amet ligula ac, aliquam pulvinar tortor. Nullam at vehicula lacus.`
export const littleLorem = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin non fermentum velit. Nunc pharetra felis ac elementum maximus. Proin efficitur dignissim vehicula. Quisque dapibus ante vel semper interdum. Etiam sem quam, varius ac diam sed, auctor imperdiet mi. Duis justo urna, gravida ut nibh quis, porta efficitur nisl. Maecenas sed.`
